FLUSH PRIVILEGES;

DROP USER IF EXISTS 'omnet'@'%';

CREATE USER 'omnet'@'%' IDENTIFIED BY 'NNNNN';

CREATE DATABASE IF NOT EXISTS omnet;

GRANT ALL PRIVILEGES ON omnet.* TO 'omnet'@'%';

FLUSH PRIVILEGES;
